apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress
spec:
    rules:
        - host: testlab3.com
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: node-port
                            port:
                                name: http
    tls:
        - hosts:
              - testlab3.com
          secretName: tls-secr
